### ISSUE TITLE
Current PHP version requirements

### ISSUE THREAD

**Issue by peter279k** [ibericode/vat#31]
As title, according to the [.travis.yml](https://github.com/ibericode/vat/blob/master/.travis.yml) file, it only tests for `php-7.3` and `php-7.4` versions.

When looking at the [composer.json](https://github.com/ibericode/vat/blob/master/composer.json) file, it requires `php-7.1` version at least.

What's the PHP versions requirements currently? If this package requires `php-7.1` and `php-7.2`, it should add above PHP version tests during Travis CI building.

Otherwise, it should modify the `composer.json` and using the `>=7.3` to let this package require `php-7.3` version at least.

Once this issue is accepted by repository owner, I will be happy to work on this.

**Comment by dannyvankooten** [comment]
Hey @peter279k 

I agree! 

As security updates for PHP 7.2 are no longer shipped in 12 days from now, I decided to bump the PHP requriement in composer.json to version 7.3 and up instead of adding the older (unsupported) PHP versions to the Travis configuration file.

Good catch, thank you!
