### ISSUE TITLE
UK/GB Vat number support

### ISSUE THREAD

**Issue by paulhennell** [ibericode/vat#49]
As of 01/01/2021 (Brexit) the Vies validator no longer supports GB VAT numbers.

Currently this library still supports validateVatNumberFormat('GB000000000') as true, but running validate on any GB code throws a ViesException of invalid input.

There is a (new) API from the UK [here](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/1.0) - Would you be open to a PR that added support for GB numbers using this or do you want to stay EU/Vies specific?

**Comment by oktaykalfa** [comment]
Hello, im having the same problem, are you considering to solve this?

**Comment by dannyvankooten** [comment]
Hello @paulhennell,

I am terribly sorry for the late reply, but at this time I would like the library to stay specific to the EU simply because that is how we're using it ourselves and I'd rather not take on the burden of maintaining parts of the library that we are not using ourselves.
