### ISSUE TITLE
CURL Refresh Fails

### ISSUE THREAD

**Issue by smuglet** [ibericode/vat#53]
This could just be my setup but I was getting failure when 

IbericodeVatRatesClient  fetch() was being called.  Returning an empty body and no status code.  Throwing an exception preventing all other code doing-the-do.

Had to add in curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,FALSE); to get it to work, not ideal as a temp mod to the main library... but might be an cert issue on the HTTPS for https://raw.githubusercontent.com/ibericode/vat-rates/master/vat-rates.json that needs resolving?  Or could be something else but this fixed it for me.

**Comment by dannyvankooten** [comment]
@smuglet I believe this usually indicates an issue with your version of OpenSSL.

**Comment by smuglet** [comment]
Thanks @dannyvankooten .  I wonder if there might be a way to make this a setting we can alter without having to adjust the source of the code itself?  Not a huge amount I can do about the version of OpenSSL I'm using unfortunately and at least that would give me an option without fiddling with the core source?  Cheers.
